name = "WebAssemblyText"
uuid = "1dd9bfdb-487e-42a5-b5b5-3cdd2428ed86"
authors = ["Anders Gustafsson <andersgee@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
